//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebService.ServiceBasicLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/WebService", ConfigurationName="ServiceBasicLogin.BasicLoginSoap")]
    public interface BasicLoginSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://localhost/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/HelloWorld", ReplyAction="*")]
        ClienteWebService.ServiceBasicLogin.HelloWorldResponse HelloWorld(ClienteWebService.ServiceBasicLogin.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebService.ServiceBasicLogin.HelloWorldResponse> HelloWorldAsync(ClienteWebService.ServiceBasicLogin.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://localhost/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Login", ReplyAction="*")]
        ClienteWebService.ServiceBasicLogin.LoginResponse Login(ClienteWebService.ServiceBasicLogin.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebService.ServiceBasicLogin.LoginResponse> LoginAsync(ClienteWebService.ServiceBasicLogin.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://localhost/WebService", Order=0)]
        public ClienteWebService.ServiceBasicLogin.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteWebService.ServiceBasicLogin.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebService")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://localhost/WebService", Order=0)]
        public ClienteWebService.ServiceBasicLogin.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteWebService.ServiceBasicLogin.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebService")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://localhost/WebService", Order=0)]
        public ClienteWebService.ServiceBasicLogin.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClienteWebService.ServiceBasicLogin.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebService")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://localhost/WebService", Order=0)]
        public ClienteWebService.ServiceBasicLogin.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClienteWebService.ServiceBasicLogin.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebService")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicLoginSoapChannel : ClienteWebService.ServiceBasicLogin.BasicLoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicLoginSoapClient : System.ServiceModel.ClientBase<ClienteWebService.ServiceBasicLogin.BasicLoginSoap>, ClienteWebService.ServiceBasicLogin.BasicLoginSoap {
        
        public BasicLoginSoapClient() {
        }
        
        public BasicLoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicLoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicLoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebService.ServiceBasicLogin.HelloWorldResponse ClienteWebService.ServiceBasicLogin.BasicLoginSoap.HelloWorld(ClienteWebService.ServiceBasicLogin.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string usuario) {
            ClienteWebService.ServiceBasicLogin.HelloWorldRequest inValue = new ClienteWebService.ServiceBasicLogin.HelloWorldRequest();
            inValue.Body = new ClienteWebService.ServiceBasicLogin.HelloWorldRequestBody();
            inValue.Body.usuario = usuario;
            ClienteWebService.ServiceBasicLogin.HelloWorldResponse retVal = ((ClienteWebService.ServiceBasicLogin.BasicLoginSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebService.ServiceBasicLogin.HelloWorldResponse> ClienteWebService.ServiceBasicLogin.BasicLoginSoap.HelloWorldAsync(ClienteWebService.ServiceBasicLogin.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebService.ServiceBasicLogin.HelloWorldResponse> HelloWorldAsync(string usuario) {
            ClienteWebService.ServiceBasicLogin.HelloWorldRequest inValue = new ClienteWebService.ServiceBasicLogin.HelloWorldRequest();
            inValue.Body = new ClienteWebService.ServiceBasicLogin.HelloWorldRequestBody();
            inValue.Body.usuario = usuario;
            return ((ClienteWebService.ServiceBasicLogin.BasicLoginSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebService.ServiceBasicLogin.LoginResponse ClienteWebService.ServiceBasicLogin.BasicLoginSoap.Login(ClienteWebService.ServiceBasicLogin.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string usuario, string password) {
            ClienteWebService.ServiceBasicLogin.LoginRequest inValue = new ClienteWebService.ServiceBasicLogin.LoginRequest();
            inValue.Body = new ClienteWebService.ServiceBasicLogin.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            ClienteWebService.ServiceBasicLogin.LoginResponse retVal = ((ClienteWebService.ServiceBasicLogin.BasicLoginSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebService.ServiceBasicLogin.LoginResponse> ClienteWebService.ServiceBasicLogin.BasicLoginSoap.LoginAsync(ClienteWebService.ServiceBasicLogin.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebService.ServiceBasicLogin.LoginResponse> LoginAsync(string usuario, string password) {
            ClienteWebService.ServiceBasicLogin.LoginRequest inValue = new ClienteWebService.ServiceBasicLogin.LoginRequest();
            inValue.Body = new ClienteWebService.ServiceBasicLogin.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((ClienteWebService.ServiceBasicLogin.BasicLoginSoap)(this)).LoginAsync(inValue);
        }
    }
}
